apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: main-eks-cluster
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: secret-manager
            namespace: external-secrets
      service: SecretsManager
      region: eu-central-1
