apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::239861161554:role/secrets-manager-irsa-role-20260302235208475500000001
  name: secret-manager
