apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-api
spec:
  project: default
  source:
    path: k8s/chart
    repoURL: https://github.com/husamuddin/fundingpips-devops-task
    targetRevision: argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - CreateNamespace=true
    automated:
      enabled: true
      prune: true
      selfHeal: true
