apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-api
spec:
  project: default
  source:
    path: k8s/chart
    repoURL: https://github.com/husamuddin/fundingpips-devops-task
    targetRevision: main
    helm:
      releaseName: api
      valuesObject:
        image:
          repository: 239861161554.dkr.ecr.eu-central-1.amazonaws.com/api
          tag: "145b9fe"
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
