apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: argo
resources:
  - ../../../base
  - ./argo-cd.yaml

patches:
  - patch: |
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: helm-api
      spec:
        source:
          helm:
            valuesObject:
              ingress:
                enabled: true
                className: nginx
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt
                  external-dns.alpha.kubernetes.io/hostname: api.fundingpips.xctl.fyi
                tls:
                  - hosts:
                      - api.fundingpips.xctl.fyi
                    secretName: api-fundingpips-xctl-fyi

                hosts:
                  - host: api.fundingpips.xctl.fyi
                    paths:
                      - path: /
                        pathType: Prefix
              env:
                - name: SECRET_KEY_BASE
                  valueFrom:
                    secretKeyRef:
                      name: api
                      key: SECRET_KEY_BASE
