apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arg-cd-github-app
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: main-eks-cluster
    kind: ClusterSecretStore
  target:
    name: arg-cd-github-app
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        githubAppID: "{{ .githubAppID }}"
        githubAppInstallationID: "{{ .githubAppInstallationID }}"
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
        type: git
        url: https://github.com/husamuddin/fundingpips-devops-task.git
  data:
    - secretKey: githubAppID
      remoteRef:
        key: argo-cd-github-app
        property: GITHUB_APP_ID
    - secretKey: githubAppInstallationID
      remoteRef:
        key: argo-cd-github-app
        property: GITHUB_APP_INSTALLATION_ID
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: argo-cd-github-app
        property: GITHUB_APP_PRIVATE_KEY
        decodingStrategy: Base64
