apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api
  namespace: api
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: main-eks-cluster
    kind: ClusterSecretStore
  target:
    name: api
    creationPolicy: Owner
    template:
      data:
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: api-service
        property: SECRET_KEY_BASE
