apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: main-eks-cluster
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
    template:
      data:
        apiKey: "{{ .apiKey }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: cloudflare-api-key
        property: apiKey
