apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tools
  namespace: argo
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/husamuddin/fundingpips-devops-task.git
              revision: main
              directories:
                - path: gitops/argo-cd/dev/eu-central-1/main-eks-cluster/argo
          - clusters: {}

    - matrix:
        generators:
          - git:
              repoURL: https://github.com/husamuddin/fundingpips-devops-task.git
              revision: main
              directories:
                - path: gitops/argo-cd/dev/eu-central-1/main-eks-cluster/*
                - path: gitops/argo-cd/dev/eu-central-1/main-eks-cluster/argo
                  exclude: true
          - clusters: {}

  template:
    metadata:
      name: "{{ index .path.segments 2 }}-{{ index .path.segments 3 }}-{{.path.basenameNormalized}}"
    spec:
      project: "tools"
      source:
        repoURL: https://github.com/husamuddin/fundingpips-devops-task.git
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: "{{.server}}"
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
