apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tools
  namespace: argo
spec:
  description: "Project for managing infrastructure applications"

  orphanedResources:
    warn: true

  sourceRepos:
    - "https://github.com/xxx/gitops.git"

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
